//
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const CREATE_FLOORPLAN_SUCCESS = "CREATE_FLOORPLAN_SUCCESS";
export const UPDATE_FLOORPLAN_SUCCESS = "UPDATE_FLOORPLAN_SUCCESS";
export const LOAD_FLOORPLANS_SUCCESS = 'LOAD_FLOORPLANS_SUCCESS';
export const CREATE_VENUE_SUCCESS = "CREATE_VENUE_SUCCESS";
export const UPDATE_VENUE_SUCCESS = "UPDATE_VENUE_SUCCESS";
export const LOAD_VENUES_SUCCESS = 'LOAD_VENUES_SUCCESS';
export const CREATE_PERFORMER_SUCCESS = "CREATE_PERFORMER_SUCCESS";
export const UPDATE_PERFORMER_SUCCESS = "UPDATE_PERFORMER_SUCCESS";
export const LOAD_PERFORMERS_SUCCESS = 'LOAD_PERFORMERS_SUCCESS';
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const CREATE_TICKET_SUCCESS = 'CREATE_TICKET_SUCCESS';
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
